### ISSUE TITLE
No v1 ref

### ISSUE THREAD

**Issue by mpalmer** [mfinelli/setup-shfmt#37]
The documentation suggests `uses: mfinelli/setup-shfmt@v1`, but there's no `v1` tag or branch, which causes GitHub Actions to be *extremely* underwhelmed:

![action](https://user-images.githubusercontent.com/357/138972285-ff945610-9288-4315-8e71-f23f31314f72.png)

I guess either switch the docs to use `@master`, or else create a `v1` tag/branch for Actions to find.

**Comment by mfinelli** [comment]
I've cut `v1.0.0` (and `v1`) tags so the documentation should be up-to-date now. I will add support for windows runners at a later date.
